function FS_lapSheet03(){
 const ss=SpreadsheetApp.getActive(),tech=ss.getSheetByName(FS_CFG.SHEETS.TECH),rev=ss.getSheetByName(FS_CFG.SHEETS.REVENUE);if(!tech||!rev)throw new Error('Cần lập 01 và 02 trước.');
 const info=FS_readInfo_(tech),months=FS_num_(info['Số tháng mô hình']),start=info['Ngày bắt đầu dự án'],costs=FS_costMap_(tech),sched=FS_readBlock_(tech,'TIEN_DO_CHI_PHI').map(r=>({item:String(r[0]||''),start:Math.max(1,FS_num_(r[1])),duration:Math.max(1,FS_num_(r[2])),rate:FS_rate_(r[3]),type:String(r[4]||'')}));
 const revData=rev.getLastRow()>1?rev.getRange(2,1,rev.getLastRow()-1,18).getValues():[];const by={};for(let t=1;t<=months;t++)by[t]={cash:0,vatOut:0,sale:0,rent:0};revData.forEach(r=>{const t=FS_num_(r[0]);if(by[t]){by[t].sale+=FS_num_(r[12]);by[t].rent+=FS_num_(r[13]);by[t].vatOut+=FS_num_(r[16]);by[t].cash+=FS_num_(r[17]);}});
 const itemNames={xd:['Chi phí XD/TB/khác','Chi phí xây dựng & thiết bị'],gpmb:['Chi phí GPMB'],land:['Tiền SDĐ/thuê đất'],htkt:['Chi phí HTKT'],sell:['Chi phí bán hàng'],reserve:['Chi phí dự phòng'],op:['Chi phí vận hành'],maint:['Chi phí bảo trì']};const items={};Object.keys(itemNames).forEach(k=>items[k]=FS_costItem_(costs,itemNames[k]));
 function scheduled(k,t){const it=items[k],rows=sched.filter(x=>FS_key_(x.item)===FS_key_(it.name)||itemNames[k].some(n=>FS_key_(x.item)===FS_key_(n)));if(!rows.length)return 0;return rows.reduce((s,x)=>{if(t<x.start||t>=x.start+x.duration)return s;const factor=(FS_key_(x.type).includes('motlan'))?(t===x.start?1:0):1/x.duration;return s+it.before*x.rate*factor;},0);}
 const rows=[];let vatCredit=0;for(let t=1;t<=months;t++){const d=FS_addMonths_(start,t-1),r=by[t];const xd=scheduled('xd',t),gpmb=scheduled('gpmb',t),land=scheduled('land',t),htkt=scheduled('htkt',t),sell=r.sale*items.sell.rate,op=r.rent*items.op.rate,maint=r.rent*items.maint.rate,reserve=(xd+htkt)*items.reserve.rate;const vatIn=xd*items.xd.vat+gpmb*items.gpmb.vat+land*items.land.vat+htkt*items.htkt.vat+sell*items.sell.vat+op*items.op.vat+maint*items.maint.vat+reserve*items.reserve.vat;const total=xd+gpmb+land+htkt+sell+op+maint+reserve,totalAfter=total+vatIn,vatPay=Math.max(0,r.vatOut-vatCredit-vatIn),vatEnd=Math.max(0,vatCredit+vatIn-r.vatOut);rows.push([t,d,d.getFullYear(),'Q'+Math.ceil((d.getMonth()+1)/3)+'/'+d.getFullYear(),r.cash,r.vatOut,xd,gpmb,land,htkt,sell,op,maint,reserve,total,vatIn,totalAfter,vatCredit,vatPay,vatEnd]);vatCredit=vatEnd;}
 const sh=FS_getOrCreateSheet_(ss,FS_CFG.SHEETS.COST);FS_resetSheet_(sh,months+1,20);sh.getRange(1,1,1,20).setValues([['Tháng số','Tháng','Năm','Quý','Dòng tiền thu khách hàng','VAT đầu ra','XD/TB trước VAT','GPMB trước VAT','Tiền SDĐ/thuê đất trước VAT','HTKT trước VAT','Chi phí bán hàng trước VAT','Chi phí vận hành trước VAT','Chi phí bảo trì trước VAT','Chi phí dự phòng trước VAT','Tổng chi trước VAT','VAT đầu vào','Tổng chi sau VAT','VAT khấu trừ đầu kỳ','VAT phải nộp','VAT khấu trừ cuối kỳ']]);sh.getRange(2,1,rows.length,20).setValues(rows);FS03_format_(sh,months+1);
}
function FS03_format_(sh,end){sh.setFrozenRows(1);sh.setFrozenColumns(4);sh.getRange(1,1,1,20).setFontWeight('bold').setBackground('#fce4d6');if(end>1){sh.getRange(2,2,end-1,1).setNumberFormat('MM/yyyy');sh.getRange(2,5,end-1,16).setNumberFormat('#,##0');}sh.autoResizeColumns(1,20);}
